/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package address.view;

import address.model.Buildings;
import address.model.CheckStreet;
import address.model.Citizen;
import javax.swing.JOptionPane;

/**
 *
 * @author Prof
 */
public class AddressAppView extends javax.swing.JFrame {

    /**
     * Creates new form AddressAppView
     */
    public AddressAppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        checkAddressTab = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        buildingIdField1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        buildingInfoBtn1 = new javax.swing.JButton();
        clearBuildingInfoBtn1 = new javax.swing.JButton();
        chkBuildingNoLabel = new javax.swing.JLabel();
        chkStreetNameLabel = new javax.swing.JLabel();
        chkDistrictNameLabel = new javax.swing.JLabel();
        chkLgaNameLabel = new javax.swing.JLabel();
        chkStateNameLabel = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        chkBuildingNameLabel = new javax.swing.JLabel();
        regNewBuildingTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regBuildNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regBuildNameOwnerField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regBuildStreetIdField = new javax.swing.JTextField();
        regTypOfBuildingComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        regChkStreetField = new javax.swing.JTextField();
        regChkStrBtn = new javax.swing.JButton();
        regChkStrClearBtn = new javax.swing.JButton();
        regBuildingBtn = new javax.swing.JButton();
        regClearBuildingBtn = new javax.swing.JButton();
        strtNameLabel = new javax.swing.JLabel();
        strtIdLabel = new javax.swing.JLabel();
        strtNamelDisplayLabel = new javax.swing.JLabel();
        strtIdDisplayLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regBuildNiField = new javax.swing.JTextField();
        regNewStreetTab = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        updateAddressTab = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        buildingIdField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        updateResetBtn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        checkStreetField = new javax.swing.JTextField();
        chkStreetBtn = new javax.swing.JButton();
        chkClearStreetBtn = new javax.swing.JButton();
        streetNameLabel = new javax.swing.JLabel();
        streetIdLabel = new javax.swing.JLabel();
        streetNameDisplayLabel = new javax.swing.JLabel();
        streetIdDisplayLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        streetIdField = new javax.swing.JTextField();
        roomNoField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        checkBuildingIdField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        chkBuildingInfoBtn = new javax.swing.JButton();
        clrChkBuildingInfoBtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        buildingNoLabel = new javax.swing.JLabel();
        nameOfBuildingInfoLabel = new javax.swing.JLabel();
        nameOfBuildingOwnerLabel = new javax.swing.JLabel();
        typeOfBuildingLabel = new javax.swing.JLabel();
        streetNameInfoLabel = new javax.swing.JLabel();
        districtNameLabel = new javax.swing.JLabel();
        lgaNameLabel = new javax.swing.JLabel();
        stateNameLabel = new javax.swing.JLabel();
        countryNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddressApp");
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        checkAddressTab.setBackground(new java.awt.Color(255, 255, 255));
        checkAddressTab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel27.setText("Building ID:");

        buildingIdField1.setBackground(new java.awt.Color(102, 102, 255));
        buildingIdField1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel28.setText("Building Number:");

        jLabel41.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel41.setText("Street Name:");

        jLabel47.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel47.setText("District Name:");

        jLabel48.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel48.setText("LGA:");

        jLabel49.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel49.setText("State");

        buildingInfoBtn1.setBackground(new java.awt.Color(102, 102, 255));
        buildingInfoBtn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        buildingInfoBtn1.setForeground(new java.awt.Color(255, 255, 255));
        buildingInfoBtn1.setText("Check");
        buildingInfoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingInfoBtn1ActionPerformed(evt);
            }
        });

        clearBuildingInfoBtn1.setBackground(new java.awt.Color(102, 102, 255));
        clearBuildingInfoBtn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        clearBuildingInfoBtn1.setForeground(new java.awt.Color(255, 255, 255));
        clearBuildingInfoBtn1.setText("Clear");
        clearBuildingInfoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBuildingInfoBtn1ActionPerformed(evt);
            }
        });

        chkBuildingNoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        chkStreetNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        chkDistrictNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        chkLgaNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        chkStateNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel55.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel55.setText("Name Of Building:");

        chkBuildingNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        javax.swing.GroupLayout checkAddressTabLayout = new javax.swing.GroupLayout(checkAddressTab);
        checkAddressTab.setLayout(checkAddressTabLayout);
        checkAddressTabLayout.setHorizontalGroup(
            checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkAddressTabLayout.createSequentialGroup()
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkAddressTabLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(checkAddressTabLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(buildingIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkAddressTabLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkBuildingNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(checkAddressTabLayout.createSequentialGroup()
                                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkStateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkLgaNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkStreetNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkDistrictNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkAddressTabLayout.createSequentialGroup()
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkBuildingNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(checkAddressTabLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(buildingInfoBtn1)
                        .addGap(67, 67, 67)
                        .addComponent(clearBuildingInfoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        checkAddressTabLayout.setVerticalGroup(
            checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkAddressTabLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(buildingIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBuildingInfoBtn1)
                    .addComponent(buildingInfoBtn1))
                .addGap(73, 73, 73)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(chkBuildingNameLabel))
                .addGap(22, 22, 22)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(chkBuildingNoLabel))
                .addGap(18, 18, 18)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(chkStreetNameLabel))
                .addGap(26, 26, 26)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(chkDistrictNameLabel))
                .addGap(18, 18, 18)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(chkLgaNameLabel))
                .addGap(18, 18, 18)
                .addGroup(checkAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(chkStateNameLabel))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Check Address", checkAddressTab);

        regNewBuildingTab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Name Of Building:");

        regBuildNameField.setBackground(new java.awt.Color(102, 102, 255));
        regBuildNameField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Name Of Building Owner");

        regBuildNameOwnerField.setBackground(new java.awt.Color(102, 102, 255));
        regBuildNameOwnerField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Type Of Building");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Street ID:");

        regBuildStreetIdField.setBackground(new java.awt.Color(102, 102, 255));
        regBuildStreetIdField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        regTypOfBuildingComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regTypOfBuildingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type Of Building", "Commercial", "Agricultural", "Residential", "Medical", "Educational", "Government", "Industrial", "Military", "Parking & Storage", "Transport", "Non-Building", "Infrastruture", "Power Provider" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Check Out Your  STREET ID  by Typing the STREET NAME");

        regChkStreetField.setBackground(new java.awt.Color(204, 204, 204));
        regChkStreetField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        regChkStrBtn.setBackground(new java.awt.Color(204, 51, 0));
        regChkStrBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        regChkStrBtn.setForeground(new java.awt.Color(255, 255, 255));
        regChkStrBtn.setText("CHECK");
        regChkStrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regChkStrBtnActionPerformed(evt);
            }
        });

        regChkStrClearBtn.setBackground(new java.awt.Color(204, 51, 0));
        regChkStrClearBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        regChkStrClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        regChkStrClearBtn.setText("CLEAR");
        regChkStrClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regChkStrClearBtnActionPerformed(evt);
            }
        });

        regBuildingBtn.setBackground(new java.awt.Color(102, 102, 255));
        regBuildingBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regBuildingBtn.setForeground(new java.awt.Color(255, 255, 255));
        regBuildingBtn.setText("Register");
        regBuildingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBuildingBtnActionPerformed(evt);
            }
        });

        regClearBuildingBtn.setBackground(new java.awt.Color(102, 102, 255));
        regClearBuildingBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regClearBuildingBtn.setForeground(new java.awt.Color(255, 255, 255));
        regClearBuildingBtn.setText("Reset");

        strtNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        strtIdLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        strtNamelDisplayLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        strtNamelDisplayLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        strtIdDisplayLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        strtIdDisplayLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Building No:");

        regBuildNiField.setBackground(new java.awt.Color(102, 102, 255));
        regBuildNiField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        javax.swing.GroupLayout regNewBuildingTabLayout = new javax.swing.GroupLayout(regNewBuildingTab);
        regNewBuildingTab.setLayout(regNewBuildingTabLayout);
        regNewBuildingTabLayout.setHorizontalGroup(
            regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regNewBuildingTabLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(regBuildNameOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(regBuildNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(regBuildStreetIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(regTypOfBuildingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(regBuildNiField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regNewBuildingTabLayout.createSequentialGroup()
                        .addComponent(regChkStrBtn)
                        .addGap(54, 54, 54)
                        .addComponent(regChkStrClearBtn)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regNewBuildingTabLayout.createSequentialGroup()
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(strtNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(regChkStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                                    .addComponent(strtNamelDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(strtIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(strtIdDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(28, 28, 28))))
            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(regBuildingBtn)
                .addGap(105, 105, 105)
                .addComponent(regClearBuildingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        regNewBuildingTabLayout.setVerticalGroup(
            regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(regChkStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regNewBuildingTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(regBuildNiField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(regBuildNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(regBuildNameOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(regTypOfBuildingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(regBuildStreetIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(regNewBuildingTabLayout.createSequentialGroup()
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regChkStrBtn)
                            .addComponent(regChkStrClearBtn))
                        .addGap(68, 68, 68)
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strtNameLabel)
                            .addComponent(strtIdLabel))
                        .addGap(26, 26, 26)
                        .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strtNamelDisplayLabel)
                            .addComponent(strtIdDisplayLabel))))
                .addGap(31, 31, 31)
                .addGroup(regNewBuildingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBuildingBtn)
                    .addComponent(regClearBuildingBtn))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Register New Building", regNewBuildingTab);

        regNewStreetTab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Name Of Street:");

        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Street ID:");

        jTextField7.setBackground(new java.awt.Color(102, 102, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setText("District ID:");

        jTextField8.setBackground(new java.awt.Color(102, 102, 255));
        jTextField8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Register");

        jButton8.setBackground(new java.awt.Color(102, 102, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Reset");

        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jTextField9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Check Out Your  DISTRICT ID  by Typing the DISTRICT NAME");

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 51));
        jButton9.setText("CHECK");

        jButton10.setBackground(new java.awt.Color(102, 102, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 0, 51));
        jButton10.setText("CLEAR");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel15.setText("DISTRICT NAME");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel16.setText("DISTRICT ID");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("Hi");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel18.setText("Hello");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout regNewStreetTabLayout = new javax.swing.GroupLayout(regNewStreetTab);
        regNewStreetTab.setLayout(regNewStreetTabLayout);
        regNewStreetTabLayout.setHorizontalGroup(
            regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regNewStreetTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(regNewStreetTabLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(jTextField7))
                        .addGroup(regNewStreetTabLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(regNewStreetTabLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(regNewStreetTabLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regNewStreetTabLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(54, 54, 54)
                        .addComponent(jButton10)
                        .addGap(87, 87, 87)))
                .addGap(29, 29, 29))
            .addGroup(regNewStreetTabLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButton7)
                .addGap(105, 105, 105)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        regNewStreetTabLayout.setVerticalGroup(
            regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regNewStreetTabLayout.createSequentialGroup()
                .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regNewStreetTabLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(regNewStreetTabLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(37, 37, 37)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addGap(24, 24, 24)
                .addGroup(regNewStreetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Register New street", regNewStreetTab);

        updateAddressTab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel19.setText("First Name:");

        firstNameField.setBackground(new java.awt.Color(102, 102, 255));
        firstNameField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel20.setText("Middle Name:");

        middleNameField.setBackground(new java.awt.Color(102, 102, 255));
        middleNameField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel21.setText("Last Name:");

        lastNameField.setBackground(new java.awt.Color(102, 102, 255));
        lastNameField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel22.setText("Room Number:");

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel23.setText("Building ID:");

        buildingIdField.setBackground(new java.awt.Color(102, 102, 255));
        buildingIdField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        updateBtn.setBackground(new java.awt.Color(102, 102, 255));
        updateBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        updateResetBtn.setBackground(new java.awt.Color(102, 102, 255));
        updateResetBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        updateResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateResetBtn.setText("Reset");
        updateResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResetBtnActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("Check Out Your  STREET ID  by Typing the STREET NAME");

        checkStreetField.setBackground(new java.awt.Color(204, 204, 204));
        checkStreetField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        chkStreetBtn.setBackground(new java.awt.Color(102, 102, 255));
        chkStreetBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        chkStreetBtn.setForeground(new java.awt.Color(255, 0, 51));
        chkStreetBtn.setText("CHECK");
        chkStreetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStreetBtnActionPerformed(evt);
            }
        });

        chkClearStreetBtn.setBackground(new java.awt.Color(102, 102, 255));
        chkClearStreetBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        chkClearStreetBtn.setForeground(new java.awt.Color(255, 0, 51));
        chkClearStreetBtn.setText("CLEAR");
        chkClearStreetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkClearStreetBtnActionPerformed(evt);
            }
        });

        streetNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        streetIdLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        streetNameDisplayLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        streetNameDisplayLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        streetIdDisplayLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        streetIdDisplayLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel29.setText("Street ID:");

        streetIdField.setBackground(new java.awt.Color(102, 102, 255));
        streetIdField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        roomNoField.setBackground(new java.awt.Color(102, 102, 255));
        roomNoField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel30.setText("Field Marked Asterik (*) are Important");

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel31.setText("( * )");

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel32.setText("( * )");

        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel34.setText("( * )");

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel35.setText("( * )");

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel36.setText("( * )");

        javax.swing.GroupLayout updateAddressTabLayout = new javax.swing.GroupLayout(updateAddressTab);
        updateAddressTab.setLayout(updateAddressTabLayout);
        updateAddressTabLayout.setHorizontalGroup(
            updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAddressTabLayout.createSequentialGroup()
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAddressTabLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(streetIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(updateAddressTabLayout.createSequentialGroup()
                                        .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel32))
                                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(73, 73, 73)
                                        .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(roomNoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                            .addComponent(lastNameField)
                                            .addComponent(buildingIdField)))
                                    .addGroup(updateAddressTabLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31)
                                        .addGap(133, 133, 133)
                                        .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updateAddressTabLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(chkStreetBtn)
                                        .addGap(54, 54, 54)
                                        .addComponent(chkClearStreetBtn)
                                        .addGap(89, 89, 89))
                                    .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(streetNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(checkStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(updateAddressTabLayout.createSequentialGroup()
                                                .addComponent(streetNameDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(streetIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(streetIdDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(updateAddressTabLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(updateBtn)
                        .addGap(105, 105, 105)
                        .addComponent(updateResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        updateAddressTabLayout.setVerticalGroup(
            updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAddressTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(10, 10, 10)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(41, 41, 41)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel36))
                .addGap(45, 45, 45)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(buildingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(50, 50, 50)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(streetIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(69, 69, 69)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(updateResetBtn))
                .addGap(241, 241, 241))
            .addGroup(updateAddressTabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(checkStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkStreetBtn)
                    .addComponent(chkClearStreetBtn))
                .addGap(61, 61, 61)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetNameLabel)
                    .addComponent(streetIdLabel))
                .addGap(26, 26, 26)
                .addGroup(updateAddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetNameDisplayLabel)
                    .addComponent(streetIdDisplayLabel))
                .addContainerGap())
        );

        jTabbedPane.addTab("Update Your Address", updateAddressTab);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel25.setText("Building ID:");

        checkBuildingIdField.setBackground(new java.awt.Color(102, 102, 255));
        checkBuildingIdField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel26.setText("Building Number:");

        chkBuildingInfoBtn.setBackground(new java.awt.Color(102, 102, 255));
        chkBuildingInfoBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        chkBuildingInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        chkBuildingInfoBtn.setText("Check");
        chkBuildingInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBuildingInfoBtnActionPerformed(evt);
            }
        });

        clrChkBuildingInfoBtn.setBackground(new java.awt.Color(102, 102, 255));
        clrChkBuildingInfoBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        clrChkBuildingInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        clrChkBuildingInfoBtn.setText("Clear");
        clrChkBuildingInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrChkBuildingInfoBtnActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel33.setText("Name Of Building:");

        jLabel37.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel37.setText("Building Owners Name:");

        jLabel38.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel38.setText("Type of Building:");

        jLabel40.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel40.setText("Street Name:");

        jLabel43.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel43.setText("District Name:");

        jLabel44.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel44.setText("LGA:");

        jLabel45.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel45.setText("State");

        jLabel46.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel46.setText("Country");

        buildingNoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        nameOfBuildingInfoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        nameOfBuildingOwnerLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        typeOfBuildingLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        streetNameInfoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        districtNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        lgaNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        stateNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        countryNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(checkBuildingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buildingNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameOfBuildingInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameOfBuildingOwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeOfBuildingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(streetNameInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(districtNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lgaNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(chkBuildingInfoBtn)
                        .addGap(67, 67, 67)
                        .addComponent(clrChkBuildingInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(checkBuildingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(buildingNoLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clrChkBuildingInfoBtn)
                            .addComponent(chkBuildingInfoBtn))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(nameOfBuildingInfoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(nameOfBuildingOwnerLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(typeOfBuildingLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(streetNameInfoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(districtNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(lgaNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(stateNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(countryNameLabel))
                .addContainerGap())
        );

        jTabbedPane.addTab("Check Building Information", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        Citizen citizen = new Citizen();
        if(firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty() || roomNoField.getText().isEmpty() || buildingIdField.getText().isEmpty() || streetIdField.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "All Field Marked Asterik(*) are Important", "Whenever", JOptionPane.ERROR_MESSAGE);
        }
        else if(middleNameField.getText().isEmpty()){
            int roomNo = Integer.parseInt(roomNoField.getText());
            int buildingId = Integer.parseInt(buildingIdField.getText());
            
            boolean update = citizen.Update(firstNameField.getText(), lastNameField.getText(), roomNo, buildingId, streetIdField.getText());
            if(update)
            {
                JOptionPane.showMessageDialog(this, "Update Was SuccessFull!!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                firstNameField.setText("");
                lastNameField.setText("");
                roomNoField.setText("");
                buildingIdField.setText("");
                streetIdField.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Something Went Wrong", "Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            int roomNo = Integer.parseInt(roomNoField.getText());
            int buildingId = Integer.parseInt(buildingIdField.getText());
            
            boolean update = citizen.Update(firstNameField.getText(),middleNameField.getText(), lastNameField.getText(), roomNo, buildingId, streetIdField.getText());
            if(update)
            {
                JOptionPane.showMessageDialog(this, "Update Was SuccessFull!!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                firstNameField.setText("");
                middleNameField.setText("");
                lastNameField.setText("");
                roomNoField.setText("");
                buildingIdField.setText("");
                streetIdField.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Something Went Wrong", "Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResetBtnActionPerformed
        // TODO add your handling code here:
            firstNameField.setText("");
            middleNameField.setText("");
            lastNameField.setText("");
            roomNoField.setText("");
            buildingIdField.setText("");
            streetIdField.setText("");
            
    }//GEN-LAST:event_updateResetBtnActionPerformed

    private void chkStreetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStreetBtnActionPerformed
        // TODO add your handling code here:
        CheckStreet check = new CheckStreet();
        if(checkStreetField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ENTER STREET NAME");
        }
        else{
            
            check.checkStreet(checkStreetField.getText());
            
            streetNameLabel.setText("STREET NAME");
            streetIdLabel.setText("STREET ID");
            streetNameDisplayLabel.setText(check.getStreetName());
            streetIdDisplayLabel.setText(check.getStreetId());
        }
    }//GEN-LAST:event_chkStreetBtnActionPerformed

    private void chkClearStreetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkClearStreetBtnActionPerformed
        // TODO add your handling code here:
            checkStreetField.setText("");
            streetNameLabel.setText("");
            streetIdLabel.setText("");
            streetNameDisplayLabel.setText("");
            streetIdDisplayLabel.setText("");
    }//GEN-LAST:event_chkClearStreetBtnActionPerformed

    private void regChkStrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regChkStrBtnActionPerformed
        // TODO add your handling code here:
         CheckStreet check = new CheckStreet();
        if(regChkStreetField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "ENTER STREET NAME");
        }
        else{
            
            check.checkStreet(regChkStreetField.getText());
            
            strtNameLabel.setText("STREET NAME");
            strtIdLabel.setText("STREET ID");
            strtNamelDisplayLabel.setText(check.getStreetName());
            strtIdDisplayLabel.setText(check.getStreetId());
        }
    }//GEN-LAST:event_regChkStrBtnActionPerformed

    private void regChkStrClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regChkStrClearBtnActionPerformed
        // TODO add your handling code here:
            regChkStreetField.setText("");
            strtNameLabel.setText("");
            strtIdLabel.setText("");
            strtNamelDisplayLabel.setText("");
            strtIdDisplayLabel.setText("");
    }//GEN-LAST:event_regChkStrClearBtnActionPerformed

    private void chkBuildingInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBuildingInfoBtnActionPerformed
        // TODO add your handling code here:
        Buildings build = new Buildings();
        if(checkBuildingIdField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Building Id field cannot be empty");
        }
        else if(!checkBuildingIdField.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Enter A valid Building ID");
        }
        else{
            int BuildingId = Integer.parseInt(checkBuildingIdField.getText());
            build.checkBuildingInfo(BuildingId);
            
            buildingNoLabel.setText(String.valueOf(build.getBuildingNo()));
            nameOfBuildingInfoLabel.setText(build.getBuildingName());
            nameOfBuildingOwnerLabel.setText(build.getBuildingNameOfOwner());
            typeOfBuildingLabel.setText(build.getBuildingType());
            streetNameInfoLabel.setText(build.getStreetName());
            districtNameLabel.setText(build.getDistrictName());
            lgaNameLabel.setText(build.getLgaName());
            stateNameLabel.setText(build.getStateName());
            countryNameLabel.setText(build.getCountryName());
        }
        
    }//GEN-LAST:event_chkBuildingInfoBtnActionPerformed

    private void clrChkBuildingInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrChkBuildingInfoBtnActionPerformed
        // TODO add your handling code here:
        
            checkBuildingIdField.setText("");
            buildingNoLabel.setText("");
            nameOfBuildingInfoLabel.setText("");
            nameOfBuildingOwnerLabel.setText("");
            typeOfBuildingLabel.setText("");
            streetNameInfoLabel.setText("");
            districtNameLabel.setText("");
            lgaNameLabel.setText("");
            stateNameLabel.setText("");
            countryNameLabel.setText("");
    }//GEN-LAST:event_clrChkBuildingInfoBtnActionPerformed

    private void buildingInfoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingInfoBtn1ActionPerformed
        // TODO add your handling code here:
        Buildings build = new Buildings();
        if(buildingIdField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Building Id field cannot be empty");
        }
        else if(!buildingIdField1.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Enter A valid Building ID");
        }
        else{
            int BuildingId = Integer.parseInt(buildingIdField1.getText());
            build.checkBuildingInfo(BuildingId);
            
            chkBuildingNameLabel.setText(build.getBuildingName());
            chkBuildingNoLabel.setText(String.valueOf(build.getBuildingNo()));
            chkStreetNameLabel.setText(build.getStreetName());
            chkDistrictNameLabel.setText(build.getDistrictName());
            chkLgaNameLabel.setText(build.getLgaName());
            chkStateNameLabel.setText(build.getStateName());

        }
        
            
    }//GEN-LAST:event_buildingInfoBtn1ActionPerformed

    private void clearBuildingInfoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBuildingInfoBtn1ActionPerformed
        // TODO add your handling code here:
            buildingIdField1.setText("");
            chkBuildingNameLabel.setText("");
            chkBuildingNoLabel.setText("");
            chkStreetNameLabel.setText("");
            chkDistrictNameLabel.setText("");
            chkLgaNameLabel.setText("");
            chkStateNameLabel.setText("");
    }//GEN-LAST:event_clearBuildingInfoBtn1ActionPerformed

    private void regBuildingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBuildingBtnActionPerformed
        // TODO add your handling code here:
        Buildings build = new Buildings();
        int buidlingNo = Integer.parseInt(regBuildNiField.getText());
        String buildingType = (String) regTypOfBuildingComboBox.getSelectedItem();
        
        if(regBuildNiField.getText().isEmpty() || regBuildNameField.getText().isEmpty() || regBuildNameOwnerField.getText().isEmpty() 
               || regBuildStreetIdField.getText().isEmpty() || regTypOfBuildingComboBox.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "All Field must be Filled","Field Not Filled",JOptionPane.INFORMATION_MESSAGE);
         }
        else if(!regBuildNiField.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Not A Valid Input for Building No.");
        }
        else{
            boolean register = build.registerBuilding(buidlingNo, regBuildNameField.getText(), regBuildNameOwnerField.getText(), buildingType, regBuildStreetIdField.getText());
            
            if(register){
                JOptionPane.showMessageDialog(this, "Building Successfully registered");
                regBuildNiField.setText("");
                regBuildNameField.setText("");
                regBuildNameOwnerField.setText(""); 
                regBuildStreetIdField.setText("");
                regTypOfBuildingComboBox.setSelectedIndex(0);
            }
            else{
                JOptionPane.showMessageDialog(this, "Something Went wrong","FAILED",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_regBuildingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddressAppView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buildingIdField;
    private javax.swing.JTextField buildingIdField1;
    private javax.swing.JButton buildingInfoBtn1;
    private javax.swing.JLabel buildingNoLabel;
    private javax.swing.JPanel checkAddressTab;
    private javax.swing.JTextField checkBuildingIdField;
    private javax.swing.JTextField checkStreetField;
    private javax.swing.JButton chkBuildingInfoBtn;
    private javax.swing.JLabel chkBuildingNameLabel;
    private javax.swing.JLabel chkBuildingNoLabel;
    private javax.swing.JButton chkClearStreetBtn;
    private javax.swing.JLabel chkDistrictNameLabel;
    private javax.swing.JLabel chkLgaNameLabel;
    private javax.swing.JLabel chkStateNameLabel;
    private javax.swing.JButton chkStreetBtn;
    private javax.swing.JLabel chkStreetNameLabel;
    private javax.swing.JButton clearBuildingInfoBtn1;
    private javax.swing.JButton clrChkBuildingInfoBtn;
    private javax.swing.JLabel countryNameLabel;
    private javax.swing.JLabel districtNameLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lgaNameLabel;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel nameOfBuildingInfoLabel;
    private javax.swing.JLabel nameOfBuildingOwnerLabel;
    private javax.swing.JTextField regBuildNameField;
    private javax.swing.JTextField regBuildNameOwnerField;
    private javax.swing.JTextField regBuildNiField;
    private javax.swing.JTextField regBuildStreetIdField;
    private javax.swing.JButton regBuildingBtn;
    private javax.swing.JButton regChkStrBtn;
    private javax.swing.JButton regChkStrClearBtn;
    private javax.swing.JTextField regChkStreetField;
    private javax.swing.JButton regClearBuildingBtn;
    private javax.swing.JPanel regNewBuildingTab;
    private javax.swing.JPanel regNewStreetTab;
    private javax.swing.JComboBox regTypOfBuildingComboBox;
    private javax.swing.JTextField roomNoField;
    private javax.swing.JLabel stateNameLabel;
    private javax.swing.JLabel streetIdDisplayLabel;
    private javax.swing.JTextField streetIdField;
    private javax.swing.JLabel streetIdLabel;
    private javax.swing.JLabel streetNameDisplayLabel;
    private javax.swing.JLabel streetNameInfoLabel;
    private javax.swing.JLabel streetNameLabel;
    private javax.swing.JLabel strtIdDisplayLabel;
    private javax.swing.JLabel strtIdLabel;
    private javax.swing.JLabel strtNameLabel;
    private javax.swing.JLabel strtNamelDisplayLabel;
    private javax.swing.JLabel typeOfBuildingLabel;
    private javax.swing.JPanel updateAddressTab;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateResetBtn;
    // End of variables declaration//GEN-END:variables
}
